name: "Docs link check"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
        cache: npm
    - name: Install
      run: npm ci
    - name: Check doc links
      run: |
        sphinx-build . -b linkcheck -d _build/doctrees _build/html
      working-directory: ./doc
