name: "Docs link check"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Display the path
      run: |
        import os
        print(os.environ['PATH'])
      shell: python
    - name: Check doc links
      run: |
        sphinx-build . -b linkcheck -d _build/doctrees _build/html
