name: "Docs link check"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check doc links
      run: |
        apt-get install python3-sphinx
        sphinx-build . -b linkcheck -d _build/doctrees _build/html
      working-directory: ./doc
