name: "Docs Check [Push]"
on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    run: |
         sphinx-build . -b linkcheck -d _build/doctrees _build/html
    with:
        docs-folder: "doc/"
